# Generated by Django 3.2 on 2022-04-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('uploadedFile', models.FileField(blank=True, null=True, upload_to='')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('user_email', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_pw', models.CharField(max_length=500)),
                ('user_nick', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
    ]
